services:
#    eb_platform.example:
#        class: EB\PlatformBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]


services:
    eb_platform.antispam:
        class: EB\PlatformBundle\Antispam\EBAntispam
        arguments:
            - "@mailer"
            - %locale%
            - 50
    eb_platform.email.application_mailer:
        class: EB\PlatformBundle\Email\ApplicationMailer
        arguments:
            - "@mailer"
    eb_platform.doctrine_listener.application_creation:
      class: EB\PlatformBundle\DoctrineListener\ApplicationCreationListener
      arguments:
        - "@eb_platform.email.application_mailer"
      tags:
        - { name: doctrine.event_listener, event: postPersist }
